Implement `URL.createObjectURL` and `URL.revokeObjectURL` methods
bytecodealliance/StarlingMonkey pull request #187
Opened 2024-12-10 17:45 UTC by andreiltd

2024-12-10 17:59 UTC, guybedford commented
Will ask @tschneidereit if he has any ideas about the UUID implementation - is there a small implementation we could inline into the codebase that avoids unnecessary code and might save some bytes? In general we want to watch binary size very carefully.

As for the request implementation it would be supporting the Blob URL everywhere we normally support a URL - so specifically `fetch(blobUrl)`.

The worker location is the base origin to use.

2024-12-10 18:17 UTC, andreiltd commented
Just for context, the size difference between the binary from main and this branch is 26KB. I'm not sure how much of this is due to the uuid crate.

2024-12-10 18:31 UTC, guybedford commented
Actually I think you could just use our existing implementation of `Crypto::random_uuid` here and then there's no need for a third-party crate.

2024-12-10 18:38 UTC, andreiltd commented
> Actually I think you could just use our existing implementation of `Crypto::random_uuid` here and then there's no need for a third-party crate.

Nice, I totally missed that :)

2024-12-19 12:30 UTC, andreiltd commented on tests/wpt-harness/expectations/fetch/api/basic/scheme-blob.sub.any.js.json
> +    "status": "FAIL"
This test checks that blob created with `type: "invalid"` should result in empty `Content-Type` header. It assumes the blob type should me mime parsable although this assumption is not consistent with other blob tests and the spec.

As stated here: https://w3c.github.io/FileAPI/#constructorBlob

> If the [type](https://w3c.github.io/FileAPI/#dfn-BPtype) member of the [options](https://w3c.github.io/FileAPI/#dom-blob-blob-blobparts-options-options) argument is not the empty string, run the following sub-steps:
> - Let t be the [type](https://w3c.github.io/FileAPI/#dfn-BPtype) dictionary member. If t contains any characters outside the range U+0020 to U+007E, then set t to the empty string and return from these substeps.
> - Convert every character in t to [ASCII lowercase](https://infra.spec.whatwg.org/#ascii-lowercase).

2024-12-19 12:48 UTC, andreiltd commented on cmake/compile-flags.cmake
> +        -std=gnu++20 -Wall -Werror -Qunused-arguments -Wimplicit-fallthrough
Sorry for the noise here. I just spent way too much time debugging problems that were result of missing break; This just helps me to remember that `switch` is not `match`.

2024-12-19 19:48 UTC, andreiltd commented on builtins/web/url.cpp
> +  if (!URL_STORE.get().put(result, obj)) {
We could probably only use `uuid` part of url as a key to save some cycles.

2025-01-10 20:25 UTC, guybedford requested changes
Just a couple of points. Having some more refactoring of shared functions into blob could be useful without introducing unnecessary dependence. Otherwise would be great to land soon.

2025-01-10 20:25 UTC, guybedford commented on builtins/web/fetch/fetch-api.cpp
> +    return api::throw_error(cx, FetchErrors::FetchNetworkError);
I suppose this is an existing issue, but I believe fetch network errors are supposed to be DOMException::raise.

2025-01-10 20:25 UTC, guybedford commented on builtins/web/fetch/fetch-api.cpp
> +    }
Could we refactor the above into a separate public function `std::tuple<size_t, size_t> Blob::extract_range(blob, std::string_view range_query)` or similar?

2025-01-13 11:26 UTC, andreiltd commented on builtins/web/fetch/fetch-api.cpp
> +    }
I think this could be done for any resource not blob only. I moved this to `fetch-utils.h` file. I hope it's fine :)

2025-01-13 11:30 UTC, andreiltd commented on builtins/web/fetch/fetch-api.cpp
> +    return api::throw_error(cx, FetchErrors::FetchNetworkError);
I tried changing this calls to `return DOMException::raise(cx, "The owls are not what they seem", "TypeError");` but then I'm getting bunch of test failures like this:

```
1:   NAME:    Fetching [PUT] URL.createObjectURL(blob) is KO
1:   MESSAGE: promise_rejects_js: function "function() { throw e }" threw object "TypeError: Invalid request method for scheme fetch" ("TypeError") expected instance of function "function TypeError() {
```

I'm not sure if it's possible to use `DOMException` the way the tests expects?

2025-01-13 17:58 UTC, guybedford commented on builtins/web/fetch/fetch-api.cpp
> +    }
Thanks, yes that works and will help us a lot to implement this at Fastly as we build our own request-response.cpp file implementation with Fastly-specific handling.

2025-01-13 18:01 UTC, guybedford commented on builtins/web/fetch/fetch-api.cpp
> +    return api::throw_error(cx, FetchErrors::FetchNetworkError);
That might be a deeper issue with our implementation of DOMException then. See here how `throw a TypeError` in the spec actually means throw a TypeError which is a DOM error - https://webidl.spec.whatwg.org/#exceptiondef-typeerror.

We can handle this in a follow-up of course, just wanted to mention.

2025-01-13 18:06 UTC, guybedford approved these changes
Would be great to get this landed asap. Ping @tschneidereit for final review.

2025-01-15 09:57 UTC, andreiltd commented on builtins/web/fetch/fetch-api.cpp
> +    return api::throw_error(cx, FetchErrors::FetchNetworkError);
> That all said, returning a network error looks like it should return a response? https://fetch.spec.whatwg.org/#concept-network-error

Indeed! It looks like there is a discrepancy between the tests and the spec. E.g. see this function: https://github.com/web-platform-tests/wpt/blob/master/fetch/api/basic/scheme-blob.sub.any.js#L22

It only expects `scheme-fetch` to throw  a `TypeError` on failure. I've added a `network_error` function that sets the response to the object according to the spec, but throws a `TypeError` anyway to be compliant with the tests.

2025-01-16 16:21 UTC, guybedford commented
Will aim to land this one later today unless there is further feedback.

2025-01-16 16:59 UTC, merged