Add implementation of `FormData` builtin
bytecodealliance/StarlingMonkey pull request #191
Opened 2024-12-23 20:14 UTC by andreiltd

2025-01-09 16:02 UTC, andreiltd commented
This one pretty much ready for review. I will keep it as a draft until dependency PRs are merged.

2025-01-10 20:37 UTC, guybedford approved these changes

2025-01-13 12:36 UTC, tschneidereit requested changes
This is looking great! There are a bunch of things still to address, but I don't think it'll take too much more work

2025-01-13 15:40 UTC, andreiltd commented on builtins/web/form-data.cpp
> +bool FormData::append(JSContext* cx, HandleObject self, std::string_view key, HandleValue value, HandleValue filename) {
There are some tests that check that if we pass `undefined` or `null` as a value that this will be serialized to string as well:

```
        assert_equals(create_formdata(['key', undefined]).get('key'), "undefined");
        assert_equals(create_formdata(['key', null]).get('key'), "null");
```

If we only allow `value.isString() || Blob::is_instance(value)) those tests will fail.  I'm not sure if this is fine?

2025-01-13 15:42 UTC, andreiltd commented on builtins/web/form-data.cpp
> +bool name_from_args(JSContext* cx, const JS::CallArgs& args, host_api::HostString& out) {
Nice!

2025-01-13 15:43 UTC, andreiltd commented on builtins/web/form-data.cpp
> +  }
Yeah, this should be aligned with the rest. Good catch!

2025-01-13 15:49 UTC, andreiltd commented on tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
> +    "status": "FAIL"
Yeah, this failure is odd, the test looks like this:

```js
  const value = new File([], "name", { lastModified: 123 });
  formData.set("file-2", value, "custom name");
  const file2 = formData.get("file-2");
  assert_not_equals(file2, value);  // ===> FAIL
```

This is the only test that perform this check. I wouldn't know why `file2` would be different than what we set. 😕

2025-01-13 17:56 UTC, guybedford commented on tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
> +    "status": "FAIL"
It seems that step 1.2 in this spec function - https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#create-an-entry will reinstance the file object when creating its entry in this case. Does that clarify or is there still an issue here?

2025-01-13 18:54 UTC, andreiltd commented on tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
> +    "status": "FAIL"
Yeah, there is something about creating a new instance that is off here.  I think spec doesn't mention the case where the value is `File` and there is no filename given:

```js
  const value = new File([], "name");
  formData.set("file-1", value);
  const file1 = formData.get("file-1");
  assert_equals(file1, value);
```

In the case above we should not create a new object. And then for all others we reinstance the file based on the steps:

> 2. If value is a string, then set value to the result of [converting](https://infra.spec.whatwg.org/#javascript-string-convert) value into a [scalar value string](https://infra.spec.whatwg.org/#scalar-value-string).
> 3. Otherwise:
>     1. If value is not a [File](https://w3c.github.io/FileAPI/#dfn-file) object, then set value to a new [File](https://w3c.github.io/FileAPI/#dfn-file) object, representing the same bytes, whose [name](https://w3c.github.io/FileAPI/#dfn-name) attribute value is "blob".
 >     2. If filename is given, then set value to a new [File](https://w3c.github.io/FileAPI/#dfn-file) object, representing the same bytes, whose [name](https://w3c.github.io/FileAPI/#dfn-name) attribute is filename.
 
 At least this resolves the issue without breaking other tests :)

2025-01-13 18:56 UTC, guybedford commented on tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
> +    "status": "FAIL"
In your first code example, a filename is being given into `formData.set`:

```
  formData.set("file-2", value, "custom name");
```

I also tried the example in Chrome and it worked as per the test. Or is this another test case you are mentioning?

2025-01-13 19:01 UTC, andreiltd commented on tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
> +    "status": "FAIL"
Yeah, there are two tests that I struggled to make working in the same time. It looks like the first test doesn't reinstance:
 
 ```js
test(() => {
  const value = new File([], "name");
  formData.set("file-1", value);
  const file1 = formData.get("file-1");
  assert_equals(file1, value);
  assert_equals(file1.constructor.name, "File");
  assert_equals(file1.name, "name");
  assert_equals(file1.type, "");
  assert_less_than(Math.abs(file1.lastModified - Date.now()), 200, "lastModified should be now");
}, "file without lastModified or custom name");

test(() => {
  const value = new File([], "name", { lastModified: 123 });
  formData.set("file-2", value, "custom name");
  const file2 = formData.get("file-2");
  assert_not_equals(file2, value);
  assert_equals(file2.constructor.name, "File");
  assert_equals(file2.name, "custom name");
  assert_equals(file2.type, "");
  assert_equals(file2.lastModified, 123, "lastModified should be 123");
}, "file with lastModified and custom name");

```

2025-01-13 19:02 UTC, andreiltd commented on tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
> +    "status": "FAIL"
^ This is now reflected in the code.

2025-01-13 20:25 UTC, guybedford commented on tests/wpt-harness/expectations/xhr/formdata/set-blob.any.js.json
> +    "status": "FAIL"
Great, marking as resolved, but reopen if there is more to discuss.

2025-01-13 20:25 UTC, guybedford commented on tests/wpt-harness/expectations/fetch/api/request/request-init-002.any.js.json
> +    "status": "FAIL"
It seems fine to add these in the follow-on with Request/Response integration.

2025-01-14 21:09 UTC, andreiltd commented
Hey!  I have a question regarding encoding `FormData` in the body initialization function: [The spec](https://fetch.spec.whatwg.org/#bodyinit-unions) says this :

> 10. Switch on object: 
>    - `FormData` 
>        - Set action to this step: run the [multipart/form-data encoding algorithm](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#multipart%2Fform-data-encoding-algorithm), with object’s [entry list](https://xhr.spec.whatwg.org/#concept-formdata-entry-list) and [UTF-8](https://encoding.spec.whatwg.org/#utf-8).
> 12. If action is non-null, then run these steps [in parallel](https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel):
>    - Run action.
>    Whenever one or more bytes are available and stream is not [errored](https://streams.spec.whatwg.org/#readablestream-errored), [enqueue](https://streams.spec.whatwg.org/#readablestream-enqueue) the result of [creating](https://webidl.spec.whatwg.org/#arraybufferview-create) a [Uint8Array](https://webidl.spec.whatwg.org/#idl-Uint8Array) from the available bytes into stream. When running action is done, [close](https://streams.spec.whatwg.org/#readablestream-close) stream.

Does this mean that I have to implement a stream encoder for `FormData`? My initial idea was to simply create a `Blob` out of `FormData`s entries, and provide a `blob.stream()` in a `extractBody` function. Something like this:

```js
const blobParts = [];
for (const { 0: name, 1: value } of formData) {
  blobParts.push(encodeBoundary(name));
  blobParts.push(value); 
}

const blob = new Blob(blobParts, { type: "multipart/form-data"});
...
stream = blob.stream();
length = blob.size
contentType = blob.type;
```

I think the problem with that approach is that constructing a new blob is blocking, e.g. if value is a `File` object, the `Blob` constructor ends up reading that file and copy its content to an internal buffer. Any ideas?

2025-01-14 22:06 UTC, guybedford commented
Afaict, avoiding the extra copy would involve implementing a custom FormDataStream or similar exactly as you say, similarly to what you did with the blob streaming. Perhaps there are parts of the low-level code that can be abstracted / shared? I guess it depends on the performance requirements - if users have a lot of data, copying everything would not only have the compute cost of the copy but also the memory cost of duplicating these items. Nice to avoid if we can?

2025-01-15 14:26 UTC, tschneidereit requested changes
Getting even closer! I once again left a bunch of comments, because this is surprisingly subtle. And would like to take another look once those are addressed—but that's not on you, it's on the spec being too subtle.

2025-01-15 14:26 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +bool FormData::append(JSContext *cx, HandleObject self, std::string_view name, HandleValue value,
(Leaving a comment on the overall function here, because I'm not sure were exactly inside the function body to leave it.)

The spec for this algorithm is a little bit weird, unfortunately, making it hard to understand what exactly is going on.

In particular, the sub-steps of step 3, interpreted precisely, would in some cases require first, in step 3.1, creating a new `File` instance with the name `"blob"`, and then immediately, in step 3.2, creating another new `File` instance with `filename` as the name. Since creating a `File` instance doesn't have observable side-effects, that is technically okay, but of course wasteful. It also confuses what actually should happen, which is one of three things:
- if `value` is a `string`, ensure that both `name` and `value` are scalar value strings, and append an entry of `{ name, value }`, and ignore `filename`
- otherwise, if `value` is a `Blob` but _not_ a `File`, _**or**_ if `filename` is given, create a new `File` instance and append an entry of `{ name, new_file }`
- otherwise, append an entry of `{ name, value }`

I think it might make sense to restructure this function to follow that logic. In that case, I would still keep the spec step comments, but add a comment explaining the restructuring.

I know I'm giving you a lot of feedback on this one function; the reason is that the spec really is very subtle here, and I want to make sure that we both get it right, and put ourselves into a position where we can understand what's going on long after we've all forgotten this discussion :)

2025-01-15 14:26 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +  if (!name_to_add) {
This still leaves `name` above unused. Maybe just remove that line and rename `name_to_add` to `name`? And I think all the `name_to_*` variables in the other functions below could just use `name`—but that's not too important.

2025-01-15 14:30 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +bool FormData::append(JSContext* cx, HandleObject self, std::string_view key, HandleValue value, HandleValue filename) {
ah, that answers my question, thanks. The reason the spec is written the way it is is that the WebIDL bindings will already have coerced `value` into either a `string` or a `Blob` (which might be a `File`). Since we're writing the coercion stuff by hand, we can't make that same assumption.

2025-01-15 14:31 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +    RootedString str(cx, JS::ToString(cx, value));
This part is I think still not addressed in the current code. Using the `core::to_scalar_value_string` function I suggested should work here.

2025-01-15 14:32 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +  if (value.isString() || value.isNullOrUndefined()) {
As mentioned in another comment, yes: that is correct, and enforced by the WebIDL interface definition.

2025-01-15 16:49 UTC, andreiltd commented on builtins/web/form-data.cpp
> +bool FormData::append(JSContext *cx, HandleObject self, std::string_view name, HandleValue value,
Right, but we still need to handle the `filename` in the second step and the logic for this should be something like this:

if `value` is a `Blob` but not a `File`, or if `filename` is given, then:

```rust
let new_file = match (is_file, maybe_filename) {
   (false, Some(filename)) => File(filename),
   (true, Some(filename)) => File(filename),
   (false, None) => File("blob"),
   (true, None) => unreachable!(),
};
```

2025-01-15 16:50 UTC, andreiltd commented on builtins/web/form-data.cpp
>      } else {
See my other comment: https://github.com/bytecodealliance/StarlingMonkey/pull/191#discussion_r1917012061

2025-01-15 16:51 UTC, andreiltd commented on builtins/web/form-data.cpp
> +        JS::GetReservedSlot(blob, static_cast<size_t>(File::Slots::LastModified)).toNumber();
This doesn't seem to work, I get `No function to call` error when I remove converting to a `Value`.

2025-01-15 16:59 UTC, andreiltd commented on builtins/web/form-data.cpp
> +bool FormData::append(JSContext *cx, HandleObject self, std::string_view name, HandleValue value,
E.g:

```js
  const value = new Blob();
  formData.set("blob-3", value, "custom name");
  const blob3 = formData.get("blob-3");
  assert_equals(blob3.name, "custom name");
  
  const value = new File([], "name");
  formData.set("file-2", value, "custom name");
  const file2 = formData.get("file-2");
  assert_equals(file2.name, "custom name");
  
  const value = new Blob();
  formData.set("blob-1", value);
  const blob1 = formData.get("blob-1");
  assert_equals(blob1.name, "blob");

  const value = new File([], "name");
  formData.set("file-1", value);
  const file1 = formData.get("file-1");
  assert_equals(file1.name, "name");


```

2025-01-15 17:20 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +bool FormData::append(JSContext *cx, HandleObject self, std::string_view name, HandleValue value,
I papered over the `filename` handling, yes. What I meant to highlight is that the key choice here is whether to create a new `File` or not, and that whether to use `"blob"` or `filename` is a nested choice in that. I.e., I'm arguing for a different factoring from you `match` expression, because whether or not to create a new `File` makes substantially more difference than what name to use.

Overall, the cleanest structure is probably
```cpp
if (!Blob::is_instance(value)) {
 // treat `value` as a string and return early
}

if (File::is_instance(value) && filename.isUndefined()) {
  // append `value` as is and return early
}

RootedValue filename_val(cx);
if (!filename.isUndefined()) {
  filename_val = // scalar version of `filename`
} else {
  filename_val = // "blob"
}

// Create the new file using `filename_val`
```

Does that make sense?

2025-01-15 17:32 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +        JS::GetReservedSlot(blob, static_cast<size_t>(File::Slots::LastModified)).toNumber();
Ah, that's almost certainly because the value has to be rooted. I'll add a new suggestion

2025-01-15 17:32 UTC, tschneidereit commented on builtins/web/form-data.cpp
> +        JS::GetReservedSlot(blob, static_cast<size_t>(File::Slots::LastModified)).toNumber();
```suggestion
    RootedValue lastModified_val(cx,
        JS::GetReservedSlot(blob, static_cast<size_t>(File::Slots::LastModified)));
```

2025-01-15 17:59 UTC, andreiltd commented on builtins/web/form-data.cpp
> +    RootedString str(cx, JS::ToString(cx, value));
Should be addressed now :)

2025-01-15 19:52 UTC, tschneidereit approved these changes
Very nice! Thank you for your patience with the long review cycles, and for getting this into great shape!

2025-01-15 19:53 UTC, merged